// Переносим тренировочные упражнения и карточки из лога
const drillQuestions = [
    // --- КАРТОЧКИ COLLOCATIONS & PHRASAL VERBS ---
    { id: 101, ruleId: "congratulate_on", text: "The whole team congratulated Billy ... his promotion.", options: ["with", "for", "on", "at"], correctIndex: 2, tutor: "Don't translate directly! 'Congratulate' is ALWAYS followed by ON." },
    { id: 102, ruleId: "verb_patterns_devote", text: "She ... all her free time to learning foreign languages.", options: ["spends", "devotes", "passes", "leaves"], correctIndex: 1, tutor: "Check the preposition! '... TO learning'. Only 'devotes' works with 'TO + -ing'." },
    { id: 103, ruleId: "news_is_police_are", text: "The police ... investigating the robbery right now.", options: ["is", "are", "was", "has been"], correctIndex: 1, tutor: "Unlike Russian, 'Police' in English is ALWAYS plural (they). 'The police ARE'." },
    { id: 104, ruleId: "a_number_of", text: "A growing number of people ... to run a business from home.", options: ["prefers", "prefer", "is preferring", "has preferred"], correctIndex: 1, tutor: "Rule: 'A number of' = many (Plural verb: prefer). 'The number of' = amount (Singular verb: prefers)." },
    { id: 105, ruleId: "so_few_many_that", text: "I've got so ... books that I can keep them all on one small shelf.", options: ["many", "few", "much", "little"], correctIndex: 1, tutor: "Think about the result! If they all fit on ONE small shelf, there are not a lot of them. 'Books' is countable -> FEW." },
    
    // --- ТРЕНИРОВКА ПРИТЯЖАТЕЛЬНОГО ПАДЕЖА ---
    { id: 106, ruleId: "possessive_plural_s", text: "I need to buy a present for my ______ (parents) anniversary.", options: ["parent's", "parents", "parents'", "parents's"], correctIndex: 2, tutor: "Plural ending in -s (parents). Just add an apostrophe at the end: parents'." },
    { id: 107, ruleId: "possessive_else", text: "Is this book yours? No, it must be ______ (somebody/else).", options: ["somebody's else", "somebody else's", "somebody elses", "somebody else"], correctIndex: 1, tutor: "Apostrophe and -s always go at the very end of the phrase: somebody else's." },
    { id: 108, ruleId: "possessive_else", text: "I didn't bring a pen, so I had to borrow ______ (everybody/else).", options: ["everybody's else", "everybody else's", "everybody elses", "everybody else"], correctIndex: 1, tutor: "The rule is strict: always attach 's to the word 'else' -> everybody else's." },
    
    // --- БОЛЬШОЙ ТРЕНИРОВКА НА ПРЕДЛОГИ (ATTITUDE TO / COPE WITH) ---
    { id: 109, ruleId: "attitude_to", text: "His attitude ______ his parents is very respectful.", options: ["with", "for", "to", "about"], correctIndex: 2, tutor: "Attitude always takes TO. Think of it as an arrow pointing to the object." },
    { id: 110, ruleId: "attitude_to", text: "I don't like her attitude ______ me.", options: ["with", "about", "to", "at"], correctIndex: 2, tutor: "Directional rule: attitude TO someone." },
    { id: 111, ruleId: "attitude_to", text: "What's your attitude ______ this problem?", options: ["to", "with", "for", "in"], correctIndex: 0, tutor: "Attitude TO a problem. Never 'with'." },
    { id: 112, ruleId: "attitude_to", text: "She has a positive attitude ______ life.", options: ["with", "about", "to", "of"], correctIndex: 2, tutor: "Attitude TO life is the only right collocation." },
    { id: 113, ruleId: "cope_with", text: "She copes ______ stress remarkably well.", options: ["at", "with", "for", "about"], correctIndex: 1, tutor: "Cope always goes with WITH when dealing with difficulties." },
    
    // --- ТРЕНИРОВКА ПРЕДЛОГОВ ИЗ БАНКА КАРТОЧКОВ ---
    { id: 114, ruleId: "congratulate_on", text: "She thanked me ______ the beautiful flowers.", options: ["on", "with", "for", "about"], correctIndex: 2, tutor: "Careful! Thank someone FOR something (reason). But congratulate someone ON." },
    { id: 115, ruleId: "congratulate_on", text: "They congratulated him ______ winning the race.", options: ["for", "with", "on", "at"], correctIndex: 2, tutor: "Congratulate ON winning. Stand on top of the world!" },
    { id: 116, ruleId: "congratulate_on", text: "I apologize ______ my terrible mistake.", options: ["on", "for", "with", "about"], correctIndex: 1, tutor: "Apologize FOR the mistake (reason/cause)." },
    { id: 117, ruleId: "congratulate_on", text: "He was punished ______ cheating on the exam.", options: ["with", "on", "for", "at"], correctIndex: 2, tutor: "Punish FOR doing something bad." },
    { id: 118, ruleId: "congratulate_on", text: "We congratulated them ______ their 50th wedding anniversary.", options: ["with", "for", "on", "about"], correctIndex: 2, tutor: "Anniversary is a milestone. Congratulate ON it." }
];

,
    // --- ТРЕНИРОВКА ТЕКСТОВЫХ ЛОВУШЕК (READING COMPREHENSION - NOW vs PAST) ---
    { id: 119, ruleId: "reading_now", reading: "I found it very hard to wake up early in my first year of university. For weeks I was late. But gradually my body adjusted, and now I wake up naturally at 6.30 a.m.", text: "What is true about the author NOW?", options: ["He still finds it hard to wake up early.", "He has got used to waking up early.", "He is always late for university."], correctIndex: 1, tutor: "Look for the present! 'But gradually my body adjusted, and now I wake up naturally'. The difficulty is over." },
    { id: 120, ruleId: "reading_now", reading: "When I started learning French, I could not roll my 'r' sound at all. I practised every day, and after a while it became easy.", text: "What is the situation now?", options: ["He still cannot pronounce the French 'r'.", "He can now pronounce the sound without difficulty.", "He gave up practicing French."], correctIndex: 1, tutor: "Chronology trap! 'After a while it became easy' means he can do it now perfectly fine." },
    { id: 121, ruleId: "reading_now", reading: "I used to be terrified of flying. Now I fly at least twice a month for work and I don't feel nervous at all.", text: "How does the author feel about flying now?", options: ["He is still scared of flying.", "He avoids flying for work.", "He no longer feels afraid when flying."], correctIndex: 2, tutor: "The marker 'Now... I don't feel nervous at all' clearly shows the fear is completely gone." },
    { id: 122, ruleId: "reading_now", reading: "At first the new software confused me. I made a lot of mistakes. But I kept using it, and today I can do everything quickly.", text: "What is said about his software skills today?", options: ["He still often gets confused by it.", "He has become proficient with the software.", "He refuses to use the new system."], correctIndex: 1, tutor: "'Today I can do everything quickly' = he became proficient. Focus on the final result." },
    
    // --- ТИПОВЫЕ ТЕКСТОВЫЕ ОБОБЩЕНИЯ (VARIETY OF PLACES) ---
    { id: 123, ruleId: "reading_chronology", reading: "Before becoming a writer, Anna worked as a waitress, a cleaner and a gardener. Only in her forties did she publish her first novel.", text: "What does the text say about Anna's working life?", options: ["She was a writer her whole life.", "She did several different types of work before writing.", "Her first job was in publishing."], correctIndex: 1, tutor: "First jobs were: waitress, cleaner, gardener. This is a classic 'variety of jobs/places' (разнообразие мест/профессий)." },
    { id: 124, ruleId: "reading_chronology", reading: "David started his career as a journalist, then moved to radio, and finally became a television presenter.", text: "What is true about David's career?", options: ["His first job was in television.", "He has worked in more than one area of the media.", "He only worked on the radio."], correctIndex: 1, tutor: "He changed fields: journalism, radio, TV. Syonynm for this is 'more than one area of the media'." },
    { id: 125, ruleId: "reading_different_way", reading: "E-books were supposed to replace printed books entirely. They did change the market, but many readers still prefer the feel of paper, so printed books survive.", text: "What does the author say about printed books?", options: ["Printed books have completely disappeared.", "E-books have not replaced printed books as much as predicted.", "Nobody reads paper books anymore."], correctIndex: 1, tutor: "The text says 'printed books survive'. This matches 'not replaced as much as predicted'." },

    // --- ЛЕКСИЧЕСКИЕ ЛОВУШКИ: ВИЗУАЛЬНО ПОХОЖИЕ СЛОВА ---
    { id: 126, ruleId: "collocations_costume", text: "The old castle had a dark, damp … where prisoners were once held.", options: ["dune", "dung", "dozen", "dungeon"], correctIndex: 3, tutor: "Dungeon — это подземелье/темница. Dune — это дюна, dung — навоз. Не путай похожие буквы!" },
    { id: 127, ruleId: "collocations_costume", text: "The artist carefully mixed the … on her palette before applying it to the canvas.", options: ["pigeons", "piglets", "pigments", "pickets"], correctIndex: 2, tutor: "Художник смешивает пигменты (pigments)! Pigeons — это голуби, piglets — поросята. Включай сканер смысла!" },
    { id: 128, ruleId: "collocations_costume", text: "The … of the new law caused widespread protests across the country.", options: ["passion", "passage", "passive", "package"], correctIndex: 1, tutor: "Принятие/прохождение закона = 'the passage of the law'. Passion — страсть, package — посылка." },
    { id: 129, ruleId: "collocations_costume", text: "The surgeon made a small … in the patient’s skin and carefully inserted the instrument.", options: ["incisor", "incision", "incense", "incentive"], correctIndex: 1, tutor: "Хирургический разрез = 'incision'. Incisor — это передний зуб (резец). Не режь пациента зубом!" },

    // --- ТРЕНИРОВКА КОНСТРУКЦИЙ С ЛИШНИМИ СЛОВАМИ (B8/B15 CONTINUOUS PASSIVE ЛОВУШКИ) ---
    { id: 130, ruleId: "extra_word_being", text: "This bridge is being built in the 18th century. (Find the extra word)", options: ["is", "being", "built", "in"], correctIndex: 1, tutor: "18 век уже давно прошел! Это факт истории, а не процесс сейчас. Должно быть просто 'was built'. Слово 'being' лишнее." },
    { id: 131, ruleId: "extra_word_being", text: "The house which is being located near the park is expensive. (Find the extra word)", options: ["which", "is", "being", "located"], correctIndex: 2, tutor: "Постоянное местоположение дома (is located) пишется без всяких процессов. 'Being' — шпион, убирай!" },
    { id: 132, ruleId: "extra_word_being", text: "The cake is being made by my grandmother every Sunday. (Find the extra word)", options: ["is", "being", "made", "every"], correctIndex: 1, tutor: "Регулярное действие по воскресеньям ('every Sunday') — это Present Simple Passive ('is made'). 'Being' здесь абсолютно лишнее." },

    // === БОЛЬШОЙ МАССИВ ИЗ КАРТОЧЕК 100+ COLLOCATIONS ===
    { id: 133, ruleId: "make_vs_do", text: "We need to make an ... to solve this difficult puzzle.", options: ["homework", "harm", "effort", "business"], correctIndex: 2, tutor: "Приложить усилие = 'MAKE an effort'. С остальными словами из списка используется глагол DO." },
    { id: 134, ruleId: "make_vs_do", text: "Don't worry about the gossip; it won't do any ... to your reputation.", options: ["decision", "harm", "mistake", "money"], correctIndex: 1, tutor: "Причинить вред = 'DO harm'. Запомни эту связку для части Б ЦТ." },
    { id: 135, ruleId: "make_vs_do", text: "The company plans to do ... with several foreign partners next year.", options: ["business", "promise", "money", "friends"], correctIndex: 0, tutor: "Вести бизнес / иметь деловые отношения = 'DO business'." },
    { id: 136, ruleId: "make_vs_do", text: "I want to do my ... on the exam to get the maximum score.", options: ["best", "choice", "discovery", "sure"], correctIndex: 0, tutor: "Сделать всё возможное / выложиться на максимум = 'DO your best'." },
    { id: 137, ruleId: "make_vs_do", text: "It's time to make a ... and choose which university you want to enter.", options: ["sport", "homework", "decision", "harm"], correctIndex: 2, tutor: "Принять решение = 'MAKE a decision'." },
    { id: 138, ruleId: "make_vs_do", text: "We quickly made ... with our new classmates during the first week.", options: ["business", "homework", "friends", "dishes"], correctIndex: 2, tutor: "Подружиться = 'MAKE friends' (создать дружеские связи)." },

    // --- КАРТОЧКИ: СВЯЗКИ С ПРЕДЛОГАМИ ---
    { id: 139, ruleId: "congratulate_on", text: "Are you aware ... the changes in the exam rules?", options: ["in", "of", "for", "with"], correctIndex: 1, tutor: "Быть в курсе / осознавать = 'be aware OF'. Запомни этот предлог." },
    { id: 140, ruleId: "congratulate_on", text: "Who is responsible ... organising the graduation party?", options: ["to", "about", "with", "for"], correctIndex: 3, tutor: "Быть ответственным ЗА что-то = 'be responsible FOR'." },
    { id: 141, ruleId: "congratulate_on", text: "Her dress is very similar ... the one I bought yesterday.", options: ["with", "to", "like", "as"], correctIndex: 1, tutor: "Похожий на что-то = 'be similar TO'. Не путай с русским предлогом!" },
    { id: 142, ruleId: "congratulate_on", text: "I am deeply disappointed ... the results of the test.", options: ["with", "of", "to", "for"], correctIndex: 0, tutor: "Быть разочарованным чем-то = 'be disappointed WITH' (или by)." },
    { id: 143, ruleId: "congratulate_on", text: "The annual sports festival will take ... in the central stadium.", options: ["action", "notes", "part", "place"], correctIndex: 3, tutor: "Происходить / иметь место = 'take PLACE'. ('Take part' — это участвовать)." },
    { id: 144, ruleId: "congratulate_on", text: "You should take ... of this unique opportunity to study abroad.", options: ["care", "action", "advantage", "risk"], correctIndex: 2, tutor: "Воспользоваться чем-то / извлечь выгоду = 'take advantage OF'." },
    { id: 145, ruleId: "congratulate_on", text: "I have get ... to waking up early because of my morning classes.", options: ["used", "rid", "touch", "permission"], correctIndex: 0, tutor: "Привыкнуть к чему-то = 'get USED to'. Действие вошло в привычку." },
    { id: 146, ruleId: "congratulate_on", text: "We must run a ... to check if the new program works correctly.", options: ["business", "test", "trouble", "time"], correctIndex: 1, tutor: "Провести тест / запустить проверку = 'run a TEST'." },
    { id: 147, ruleId: "congratulate_on", text: "If you break the ..., you will have to pay a very heavy fine.", options: ["habit", "rules", "law", "promise"], correctIndex: 2, tutor: "Нарушить закон = 'break the LAW'. (Нарушить правила — break the rules, но штраф платят за закон)." },
{ id: 148, ruleId: "tenses_past_perfect", text: "People _______ in the Amazon Basin for 10,000 years when it was 'first discovered' by Francisco de Orellana in 1542.", options: ["lived", "have lived", "had lived", "were living"], correctIndex: 2, tutor: "Два действия в прошлом. Одно произошло РАНЬШЕ другого (сначала жили 10 000 лет, а ПОТОМ их открыли). Для предпрошедшего действия нужен Past Perfect (had + V3)." },
  { id: 149, ruleId: "dialogue_responses", text: "— Thanks for showing me around the city.\n— _______", options: ["Nothing at all.", "Certainly.", "That makes sense.", "That’s all right!"], correctIndex: 3, tutor: "Вежливый и естественный аналог 'Пожалуйста/Не за что' в ответ на благодарность — это 'That’s all right!'." },
  { id: 150, ruleId: "extra_words", text: "I think of myself as quite both an organised person... I couldn't care it less. (Выпиши два лишних слова)", options: ["quite, about", "both, it", "an, less", "both, about"], correctIndex: 1, tutor: "Слово 'both' требует пары 'and'. А в идиоме 'couldn't care less' (мне абсолютно плевать) местоимение 'it' искусственно вставлено и ломает фразу!" },
  { id: 151, ruleId: "so_such_few_little", text: "Walking burns so _______ calories that I think I should join a gym.", options: ["little", "few", "much", "many"], correctIndex: 1, tutor: "Слово 'calories' — исчисляемое (можно посчитать). Раз он хочет в зал, ходьба сжигает МАЛО калорий. Ответ — FEW!" },
  { id: 152, ruleId: "question_tags", text: "We seldom receive so many complaints, _______?", options: ["don't we", "do we", "isn't it", "aren't we"], correctIndex: 1, tutor: "Слово 'seldom' (редко) делает первую часть ОТРИЦАТЕЛЬНОЙ. Значит, хвостик должен быть утвердительным: 'do we?'." },
  { id: 153, ruleId: "tenses_past_simple", text: "In 2010, a huge earthquake _______ Haiti, causing the deaths of over a hundred thousand people.", options: ["has hit", "was hit", "hit", "has been hitting"], correctIndex: 2, tutor: "В тексте стоит четкий маркер 'In 2010'. Это момент в прошлом, отрезанный от настоящего. Нужен чистый Past Simple — 'hit'." },
  { id: 154, ruleId: "pronouns_either", text: "Are _______ of you two interested in coming with me?", options: ["either", "none", "any", "anybody"], correctIndex: 0, tutor: "Ключевая подсказка — 'of you TWO'. Слова 'any' и 'none' работают, только если вариантов три или больше. Для ДВУХ работает 'either'." },
  { id: 155, ruleId: "make_vs_do", text: "If you take into account how young Sam is, you must admit he is DOING excellent progress (4) as a doctor.", options: ["Фрагмент 4 верный", "Фрагмент 4 содержит ошибку", "Фрагмент 2 содержит ошибку", "Фрагмент 3 содержит ошибку"], correctIndex: 1, tutor: "Progress — это результат усилий. В английском языке это жесткое устойчивое выражение: 'to MAKE progress'." },
  { id: 156, ruleId: "lexis_connect", text: "Over time, they learned to _______ getting food with the celebrity’s photograph.", options: ["attach", "tie", "connect", "adapt"], correctIndex: 2, tutor: "Установление мысленной ассоциативной связи между А и Б — это конструкция 'to connect A with B'." },
  { id: 157, ruleId: "possessive_case", text: "Ruby never seems to think about other peoples' feelings (2)...", options: ["Фрагмент 2 верный", "Фрагмент 2 содержит ошибку", "Фрагмент 1 содержит ошибку", "Ошибок нет"], correctIndex: 1, tutor: "Слово 'people' — это уже множественное число без окончания -s. Притяжательный падеж к таким словам добавляется через 's (people's)." },
  { id: 158, ruleId: "make_vs_do", text: "...and scientists are making a lot of research (3) in this area.", options: ["Фрагмент 3 верный", "Фрагмент 3 содержит ошибку", "Фрагмент 2 содержит ошибку", "Ошибок нет"], correctIndex: 1, tutor: "Research (исследование) — неисчисляемое. Никогда не используется с 'make'. Правильно: 'doing research' или 'conducting research'." },
  { id: 159, ruleId: "phrasal_verbs", text: "The cap was designed as a way of _______ the sun out of baseball players' eyes.", options: ["taking", "protecting", "keeping", "stopping"], correctIndex: 2, tutor: "Фраза 'не допускать внутрь, ограждать от проникновения' с предлогом OUT — это фразовый глагол 'to keep something out'!" },
  { id: 160, ruleId: "lexis_mean", text: "By 1970s, new technology _______ that it was possible to embroider images onto caps.", options: ["allowed", "made", "told", "meant"], correctIndex: 3, tutor: "Глагол 'mean' в значении 'означать, вести к тому что' идеально дружит с придаточными через that: 'Technology meant that...'." },
  { id: 161, ruleId: "tenses_past_continuous_passive", text: "Howard Hamilton and his wife _______ asleep when they heard a big bang.", options: ["were going", "have gone", "had gone", "were just fallen"], correctIndex: 3, tutor: "Они УЖЕ спали в тот момент. Состояние прошедшего времени передается через 'were just fallen asleep' (были уснувшими)." },
  { id: 162, ruleId: "possessive_else", text: "...of simply reporting someone's else words (3) when writing your own notes.", options: ["Фрагмент 3 верный", "Фрагмент 3 содержит ошибку", "Фрагмент 4 содержит ошибку", "Ошибок нет"], correctIndex: 1, tutor: "Апостроф и 's вешаются строго на само слово ELSE, на самый конец конструкции. Правильно: 'someone else's'." },
  { id: 163, ruleId: "tenses_present_perfect", text: "The Alex Rider books _______ English teachers very happy because they have helped a whole generation...", options: ["have made", "were made", "had made", "will be made"], correctIndex: 0, tutor: "Книги порадовали учителей, и этот результат актуален сейчас. Второго действия в прошлом нет, поэтому Past Perfect не нужен. Ответ — have made." },
  { id: 164, ruleId: "relative_clauses_which", text: "More than 22 million tourists visit Venice every year, _______ is good for businesses.", options: ["it", "which", "what", "this"], correctIndex: 1, tutor: "Запятая + WHICH! Если мы описываем ВСЮ предыдущую ситуацию целиком ('и это хорошо...'), мы пишем WHICH." },
  { id: 165, ruleId: "tenses_past_continuous", text: "I remember when I _______ to find tickets to the cup final last season!", options: ["was tried", "have tried", "was trying", "had tried"], correctIndex: 2, tutor: "Автор вспоминает прошлые долгие усилия, сам затяжной процесс поиска билетов. Нужен Past Continuous — 'was trying'." },
  { id: 166, ruleId: "tenses_present_perfect_cont", text: "You _______ the game for ages before I joined you at your table.", options: ["had watched", "were watching", "have been watching", "have watched"], correctIndex: 2, tutor: "Действие длилось ДО момента в прошлом ('before I joined') в течение долгого времени ('for ages'). Акцент на длительности — Present Perfect Continuous." },
  { id: 167, ruleId: "lexis_suited", text: "...small compartments with little bits of food that are _______ to their small appetites.", options: ["done", "preferred", "matched", "suited"], correctIndex: 3, tutor: "Когда еда или вещь соответствует потребностям, аппетиту или возможностям, используется устойчивое выражение 'be suited to'!" },
  { id: 168, ruleId: "relative_clauses_which", text: "...many plants and insects that are equally threatened, _______ people often forget about.", options: ["that", "which", "what", "whom"], correctIndex: 1, tutor: "Местоимение 'that' никогда не используется после запятой в таких придаточных. Пиши только WHICH." },
  { id: 169, ruleId: "tenses_present_perfect", text: "However, some local people say that they _______ the animals themselves.", options: ["are seen", "were seeing", "had seen", "have seen"], correctIndex: 3, tutor: "Местные жители констатируют факт из своего жизненного опыта (видели существ). Точной даты нет. Опыт без даты = Present Perfect (have seen)." },
  { id: 170, ruleId: "phrasal_verbs_take", text: "So why take _______ photography?", options: ["in", "up", "over", "on"], correctIndex: 1, tutor: "Начать с нуля заниматься спортом или увлечься новым хобби — это фразовый глагол 'to take up'." },
  { id: 171, ruleId: "dependent_prepositions", text: "Huge mountains make take-off just as difficult to _______ with.", options: ["handle", "manage", "succeed", "cope"], correctIndex: 3, tutor: "Глаголы handle и manage используются без предлогов. А вот глагол 'cope' (справляться) намертво привязан к предлогу 'with'." },
  { id: 172, ruleId: "lexis_check", text: "And if you fly, you can always _______ the length of the runway first.", options: ["control", "examine", "decide", "check"], correctIndex: 3, tutor: "Для быстрой, рутинной проверки технических параметров или цифр используется глагол 'check'." },
  { id: 173, ruleId: "tenses_past_simple", text: "The Gothic architecture appealed to Tim Burton, when he _______ it.", options: ["has seen", "saw", "had seen", "was seen"], correctIndex: 1, tutor: "Речь идет о точном моменте, когда режиссер впервые увидел дом. Завершенный факт из прошлого = Past Simple (saw)." },
  { id: 174, ruleId: "articles_the", text: "The chef started his campaign by meeting with _______ prime minister...", options: ["a", "—", "the", "an"], correctIndex: 2, tutor: "Премьер-министр в стране один, должность уникальная — ставим определенный артикль THE." },
  { id: 175, ruleId: "lexis_idioms", text: "...as teens often express online what they're reluctant to say in _______.", options: ["open", "real", "person", "face"], correctIndex: 2, tutor: "Устойчивая идиома для обозначения личного, живого общения тет-а-тет — это 'in person'." },
  { id: 176, ruleId: "phrasal_verbs_addicted", text: "However, I bet you'll get _______ to it!", options: ["keen", "fascinated", "addicted", "interested"], correctIndex: 2, tutor: "Слово 'keen' требует предлога 'on', 'interested' — 'in'. А вот предлог 'to' идеально подходит к выражению 'get addicted to' (подсесть на)." },
  { id: 177, ruleId: "tenses_past_simple", text: "The Shard _______ the tallest building in Europe when construction work was completed in 2012.", options: ["became", "was becoming", "had become", "becomes"], correctIndex: 0, tutor: "Констатация факта в прошлом, совпавшая с моментом завершения стройки. Никакого предпрошедшего времени тут нет, нужен Past Simple." },
  { id: 178, ruleId: "tenses_present_simple", text: "This clever use of glass _______ the appearance of the Shard to vary according to the weather.", options: ["is caused", "causes", "had caused", "caused"], correctIndex: 1, tutor: "Свойство здания менять вид — это постоянная архитектурная характеристика. Закон природы предмета = Present Simple (causes)." },
  { id: 179, ruleId: "pronouns_neither", text: "The two candidates applied for the post, but _______ of them had the qualifications.", options: ["none", "neither", "no one", "any"], correctIndex: 1, tutor: "Кандидатов ровно ДВОЕ. Отрицание 'none' используется от трех объектов. Для пары подходит исключительно NEITHER." },
  { id: 180, ruleId: "sequence_of_tenses", text: "Later, the woman said that she and her family _______ the dog.", options: ["have adopted", "adopted", "will adopt", "would adopt"], correctIndex: 3, tutor: "Согласование времен! Главный глагол в прошедшем времени (SAID). Значит, планы ('will adopt') сдвигаются в 'would' (Future-in-the-Past)." },
  { id: 181, ruleId: "lexis_other", text: "There were no _______ reasons for his behaving like that.", options: ["whole", "other", "another", "else"], correctIndex: 1, tutor: "Слово 'whole' означает целый объект. А когда мы говорим про дополнительные, иные причины — пишем OTHER." },
  { id: 182, ruleId: "tenses_past_perfect", text: "Charlotte was telling everyone that he _______ her life.", options: ["has saved", "would save", "was saved", "had saved"], correctIndex: 3, tutor: "Прошлое до прошлого! Пес спас девочку ДО ее рассказа (was telling). Для более раннего действия в прошлом нужен Past Perfect (had saved)." },
  { id: 183, ruleId: "tenses_past_continuous", text: "I said a tearful goodbye to my mum at the door and I _______ in front of the new class.", options: ["stand", "have stood", "was standing", "have been standing"], correctIndex: 2, tutor: "Автор описывает длительное состояние, которое служило живым фоном для истории: он стоял перед классом. Это Past Continuous (was standing)." },
  { id: 184, ruleId: "sequence_of_tenses", text: "I felt the whole class looking at me, waiting to see what I _______ .", options: ["am doing", "have done", "will do", "would do"], correctIndex: 3, tutor: "Главный глагол в прошедшем (I felt). Будущее внутри прошлого (что он сделает) передается только через WOULD + глагол." },
  { id: 185, ruleId: "collocations_attention", text: "...although recently much more attention has been _______ to it.", options: ["put", "paid", "allowed", "done"], correctIndex: 1, tutor: "Запоминай фразу целиком: 'to pay attention'. В пассивном залоге структура сохраняется: 'attention has been PAID'." },
  { id: 186, ruleId: "tenses_present_simple_passive", text: "SwimFin _______ in over 100 countries around the world.", options: ["currently sold", "will currently sell", "is currently sold", "was currently selling"], correctIndex: 2, tutor: "Продукт продают люди, нужен пассив (Passive Voice). Наречие 'currently' указывает на Present Simple. Итог — 'is currently sold'." },
  { id: 187, ruleId: "articles_the_a", text: "A boy from Texas is eligible for _______ award of the most creative cheat... he is no longer allowed to sit by _______ window in exams!", options: ["an, —", "the, —", "the, a", "—, a"], correctIndex: 2, tutor: "Награда конкретизирована ('за самого креативного...') — THE. А окно — это просто тип места, общее правило безопасности — A." },
  { id: 188, ruleId: "word_formation_nouns", text: "In free-diving there are no _______ (COMPETE) around you.", options: ["competition", "competitions", "competitor", "competitors"], correctIndex: 3, tutor: "Предлог 'around you' требует людей-одушевленных объектов. Вокруг стоят соперники во множественном числе — COMPETITORS." },
  { id: 189, ruleId: "tenses_past_simple", text: "Although an initial search _______ nothing, a crew spotted Echo.", options: ["was finding", "has found", "found", "was found"], correctIndex: 2, tutor: "Перечисление законченных событий (шторм набежал, поиск ничего не дал). Это обычное повествование, нужен Past Simple — 'found'." },
  { id: 190, ruleId: "singular_nouns_s", text: "Phonetics _______ commonly used in language teaching these days.", options: ["is", "are", "be", "was"], correctIndex: 0, tutor: "Названия наук на -ics в английском всегда ЕДИНСТВЕННОГО числа. Мысленно заменяй их на 'it'. Ответ — IS." },
  { id: 191, ruleId: "pronouns_one_another", text: "The friends travelled around the city to explore new places together and enjoy _______ another's company.", options: ["each", "one", "some", "every"], correctIndex: 1, tutor: "В тексте уже напечатано слово 'another'. Гибрида 'each another' не существует! Раз видишь 'another' — перед ним может стоять только ONE." }

// Автоматически добавляем эти тренировочные вопросы в общую базу при загрузке страницы
questionsData.push(...drillQuestions);

// Обновляем веса правил, чтобы новые вопросы тоже крутились в рулетке
drillQuestions.forEach(q => {
    if (!rulesWeight[q.ruleId]) {
        rulesWeight[q.ruleId] = 1;
    }
});
